@rem Gradle bootstrap script for crush-claw Android port
@rem Download and set up the Gradle wrapper if not already present.

@echo off
setlocal

set GRADLE_VERSION=8.10.2
set GRADLE_ZIP=gradle-%GRADLE_VERSION%-bin.zip
set GRADLE_URL=https://services.gradle.org/distributions/%GRADLE_ZIP%

cd /d "%~dp0"

if not exist "gradle\wrapper\gradle-wrapper.jar" (
    echo Downloading Gradle wrapper jar...
    curl -L -o gradle\wrapper\gradle-wrapper.jar "https://raw.githubusercontent.com/gradle/gradle/v%GRADLE_VERSION%/gradle/wrapper/gradle-wrapper.jar"
    if errorlevel 1 (
        echo Failed to download gradle-wrapper.jar
        echo Please manually download gradle-wrapper.jar into gradle\wrapper\
        echo from: https://services.gradle.org/distributions
        exit /b 1
    )
    echo Downloaded gradle-wrapper.jar
)

if not exist "gradlew.bat" (
    echo Creating gradlew.bat...
    (
        echo @rem Gradle startup script for Windows
        echo @rem Generated by crush-claw bootstrap
        echo @if "%%DEBUG%%" == "" @echo off
        echo @rem Set local scope for the variables with windows NT shell
        echo if "%%OS%%"=="Windows_NT" setlocal
        echo set DIRNAME=%%~dp0
        echo if "%%DIRNAME%%" == "" set DIRNAME=.
        echo set APP_BASE_NAME=%%~n0
        echo set APP_HOME=%%DIRNAME%%
        echo @rem Resolve any "." and ".." in APP_HOME to make it shorter.
        echo for %%%%i in ("%%APP_HOME%%") do set APP_HOME=%%%%~fi
        echo set CLASSPATH=%%APP_HOME%%\gradle\wrapper\gradle-wrapper.jar
        echo @rem Execute Gradle
        echo java.exe -classpath "%%CLASSPATH%%" org.gradle.wrapper.GradleWrapperMain %%*
    ) > gradlew.bat
    echo Created gradlew.bat
)

echo.
echo Gradle wrapper ready. Run:
echo   gradlew.bat assembleDebug
echo to build the Android APK.
echo.
echo NOTE: Requires Android SDK at D:\Android_SDK
echo       Set ANDROID_HOME=D:\Android_SDK if not already set.

endlocal
