/*
 * esp_board_manager_includes.h — simulator stub
 *
 * Provides the type definitions, CONFIG guards, and function declarations
 * needed by lua_module_board_manager.c to compile in the desktop simulator.
 *
 * On real ESP32 hardware this header is generated by the board-support package.
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Feature toggles (mimic CONFIG_* from ESP-IDF Kconfig) ---- */

#define CONFIG_ESP_BOARD_DEV_DISPLAY_LCD_SUPPORT    1
#define CONFIG_ESP_BOARD_DEV_CAMERA_SUPPORT          0
#define CONFIG_ESP_BOARD_DEV_LCD_TOUCH_I2C_SUPPORT   0
#define CONFIG_ESP_BOARD_DEV_AUDIO_CODEC_SUPPORT     0
#define CONFIG_SOC_I2S_SUPPORTS_TDM                  0
#define CONFIG_SOC_I2S_SUPPORTS_PDM_TX               0
#define CONFIG_SOC_I2S_SUPPORTS_PDM_RX               0

/* ---- Opaque handles used by board_manager device structs ---- */

#include "esp_lcd_touch.h"  /* for esp_lcd_touch_handle_t */

/* ---- Device names ---- */

#define ESP_BOARD_DEVICE_NAME_DISPLAY_LCD   "display_lcd"
#define ESP_BOARD_DEVICE_NAME_CAMERA        "camera"
#define ESP_BOARD_DEVICE_NAME_LCD_TOUCH_I2C "lcd_touch_i2c"
#define ESP_BOARD_DEVICE_NAME_AUDIO_CODEC   "audio_codec"

/* ---- dev_display_lcd_handles_t ---- */

typedef struct {
    void *panel_handle;
    void *io_handle;
} dev_display_lcd_handles_t;

typedef struct {
    int         lcd_width;
    int         lcd_height;
    const char *sub_type;       /* "io", "rgb", "dsi", or NULL */
} dev_display_lcd_config_t;

/* ---- dev_camera_handle_t ---- */

typedef struct {
    const char *dev_path;
    const char *meta_path;
} dev_camera_handle_t;

/* ---- dev_lcd_touch_i2c_handles_t ---- */

typedef struct {
    esp_lcd_touch_handle_t touch_handle;
} dev_lcd_touch_i2c_handles_t;

/* ---- Audio codec (stubbed out, not compiled) ---- */

typedef enum {
    DEV_AUDIO_CODEC_DATA_IF_TYPE_NONE = 0,
    DEV_AUDIO_CODEC_DATA_IF_TYPE_I2S,
    DEV_AUDIO_CODEC_DATA_IF_TYPE_ADC,
} dev_audio_codec_data_if_type_t;

typedef struct {
    uint32_t sample_rate_hz;
    uint8_t  pattern_num;
} board_codec_adc_t;

typedef enum {
    I2S_COMM_MODE_NONE = 0,
    I2S_COMM_MODE_STD,
    I2S_COMM_MODE_TDM,
    I2S_COMM_MODE_PDM,
} i2s_comm_mode_t;

typedef enum {
    I2S_SLOT_MODE_MONO = 0,
    I2S_SLOT_MODE_STEREO,
} i2s_slot_mode_t;

#define I2S_DIR_TX  (1 << 0)
#define I2S_DIR_RX  (1 << 1)

/* Minimal forward-declaration of periph_i2s_config_t
   (real struct is large — only the fields accessed by board_manager are used) */
typedef struct {
    i2s_comm_mode_t mode;
    uint8_t         direction;
    union {
        struct {
            struct {
                uint32_t sample_rate_hz;
            } clk_cfg;
            struct {
                i2s_slot_mode_t slot_mode;
                uint8_t         data_bit_width;
            } slot_cfg;
        } std;
    } i2s_cfg;
} periph_i2s_config_t;

typedef struct {
    const char             *name;
    dev_audio_codec_data_if_type_t data_if_type;
    bool                    adc_enabled;
    bool                    dac_enabled;
    float                   adc_init_gain;
    board_codec_adc_t       adc_cfg;
    struct {
        const char *name;
    } i2s_cfg;
} dev_audio_codec_config_t;

typedef struct {
    void *codec_dev;
} dev_audio_codec_handles_t;

/* ---- esp_board_info_t ---- */

typedef struct {
    const char *name;
    const char *chip;
    const char *version;
    const char *description;
    const char *manufacturer;
} esp_board_info_t;

/* ---- Board manager API (all stubs return ESP_ERR_NOT_SUPPORTED by default
        except display-related which return valid simulator values) ---- */

esp_err_t esp_board_manager_get_board_info(esp_board_info_t *info);
esp_err_t esp_board_manager_get_device_handle(const char *name, void **handle);
esp_err_t esp_board_manager_get_device_config(const char *name, void **config);
esp_err_t esp_board_manager_get_periph_config(const char *name, void **config);
esp_err_t esp_board_manager_init_device_by_name(const char *name);
esp_err_t esp_board_manager_deinit_device_by_name(const char *name);

#ifdef __cplusplus
}
#endif
